### ISSUE TITLE
AM/PM tag interfered with time parsing

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/anytime#10]
```
> anytime('12/17/1996 04:00:00')
[1] "1996-12-17 04:00:00 EST"
> anytime('12/17/1996 04:00:00 PM')
[1] "1996-12-17 EST"
```

**Comment by eddelbuettel** [comment]
Please use `anytime:::testFormat(fmt, timestr)` to try a few different format string to see if we can overcome this.  

For now I'd be inclined to leave things as they are as your first format is WAY more common than the second one.  

In general, use ISO formats where you can.  No AM/PM nonsense there ;-)   In all seriousness we will _never_ get all possible inputs.  We just want the sensible ones -- and again, the first wins over the second.

**Comment by eddelbuettel** [comment]
Apologies.  `testFormat()` is not yet released and only on GH.

And it does not seem to work on input with `%p` or `%P`:

``` r
> library(anytime)
> anytime:::testFormat("%m/%d/%Y %I:%M:%S %p", "12/17/1996 04:00:00 PM") 
[1] NA
> anytime:::testFormat("%m/%d/%Y %I:%M:%S", "12/17/1996 04:00:00 PM") 
[1] NA
> anytime:::testFormat("%m/%d/%Y %H:%M:%S", "12/17/1996 04:00:00 PM") 
[1] "1996-12-17 04:00:00 CST"
> anytime:::testFormat("%m/%d/%Y %I:%M:%S %p", "12/17/1996 04:00:00 PM") 
[1] NA
> anytime:::testFormat("%m/%d/%Y %I:%M:%S %P", "12/17/1996 04:00:00 PM") 
[1] NA
> 
```

So for non-ISO formats you get to use `strptime()` as before.  Sorry.

**Comment by dracodoc** [comment]
OK, got it. It's not really a problem, I was just random testing out of curious using [some inputs I saw before](http://stackoverflow.com/questions/30338735/why-r-package-lubridate-cant-parse-vector-with-multiple-formats/33452653#33452653).

**Comment by eddelbuettel** [comment]
I had ran into this before. It seems like we _should_ get this one, but no beans (as shown).

Another annoying one is that 8/9/2016 fails.  08/09/2016 works.  Oh well.   Boost bugs :)

**Comment by eddelbuettel** [comment]
Oh, and locale is a good one too.  We _may_ be able to do better than we do now.  Trouble is that we currently set things up _once_ at package load.  I guess we could offer a way to trash the data structure and rebuild it with a locale.   If that interests you ... we're always open for good PRs :)  

These days I live in a world where the default `C` locale works by default  (though I used to live elsewhere) so I won't be likely to work on this.

**Comment by dracodoc** [comment]
Yes, so many things can bite you in date, time, locale, timezone, DST, ... 
Everybody's life will be much easier if all follow a good standard.

**Comment by eddelbuettel** [comment]
Yep I must have about five or more packages dealing with different aspects of this ...
