### ISSUE TITLE
UK v US formats

### ISSUE THREAD

**Issue by mike42trees** [eddelbuettel/anytime#105]
My date format is dd/mm/yyyy (i.e. UK) but anytime interprets it as US mm/dd/yyyy
Is there a quick fix?

```r
> anytime('12/07/2012 13:48:30')
[1] "2012-12-07 14:48:30 GMT"
> anytime('13/07/2012 02:00:00')
[1] NA
```

**Comment by eddelbuettel** [comment]
You can check the lists of formats (`getFormats()`), and alter it: 

```r
R> addFormats("%d/%m/%Y %H:%M:%S")
R> anytime("12/07/2012 13:48:30")
[1] "2012-07-12 13:48:30 CDT"
R> anytime("13/07/2012 02:00:00")
[1] "2012-07-13 02:00:00 CDT"
R> 
```

Because of the possible ambiguity, d-m-y order is supported by default only with a dot rather thnan a slash (which in North America is used with m-d-y).

**Comment by mike42trees** [comment]
OK Thanks
 
Mike
