### ISSUE TITLE
Promblems if NA first in vector

### ISSUE THREAD

**Issue by eribul** [eddelbuettel/anytime#11]
A vector with date and NA (in that order) works as expected:

``` r
> anytime::anydate(c(Sys.Date(), NA))
[1] "2016-10-06" NA          
```

But the reversed order does not:

``` r
> anytime::anydate(c(NA, Sys.Date()))
Error in as.POSIXlt.numeric(anytime(x = x, tz = tz)) : 
  'origin' must be supplied
```

Would it be possible to recognise dates even if proceeded by NA:s?

**Comment by eddelbuettel** [comment]
That looked puzzling for a moment but I don't think it is us:

``` r
R> dates <- Sys.Date() + 0:3
R> dates[2] <- NA
R> dates
[1] "2016-10-06" NA           "2016-10-08" "2016-10-09"
R> anytime::anydate(dates)
[1] "2016-10-05" NA           "2016-10-07" "2016-10-08"
R> dates <- Sys.Date() + 0:3
R> dates[1] <- NA
R> anytime::anydate(dates)
[1] NA           "2016-10-06" "2016-10-07" "2016-10-08"
R> 
```

See how this process the dates irrespective of where the NA occurs?   I suspect what we have in your example is R changing the _vector_ types based on the first element:

```
R> str(c(NA, Sys.Date()))
 num [1:2] NA 17080
R> str(c(Sys.Date(), NA))
 Date[1:2], format: "2016-10-06" NA
R> 
```

We simply don't currently parse `integers` or `numeric` in that range, just how we do not parse `POSIXct` converted to numeric.

**Comment by eribul** [comment]
I just tried the same thing again with the latest version (0.0.4).
I now get a different result but still not really what I expect :-)
Maybe it is simply not supported still but I was just suprised to see this:

``` r
> anydate(c(Sys.Date(), NA))
[1] "2016-10-21" NA          
> anydate(c(NA, Sys.Date()))
[1] NA           "1970-01-01"
```

**Comment by eddelbuettel** [comment]
That is _still_ the same problem are your two input vectors are of DIFFERENT type before we see them:

```
R> class(c(NA, Sys.Date()))
[1] "numeric"
R> class(c(Sys.Date(), NA))
[1] "Date"
R> 
```

There is nothing we can do about R's casting / conversion rules.  I don't really know how to catch that value of the 17095 range we currently for the date when (forcefully) converted this.

I'll had a note to the documentation that _leading_ NA are dangerous for this reason.
