### ISSUE TITLE
Time is silently scrubbed when using certain string date time formats

### ISSUE THREAD

**Issue by estern95** [eddelbuettel/anytime#111]
Hi, Thank you for your  work on this package. I am encountering what I think is a bug.
When using anytime::anytime with dates like this:
```
11/26/2018 2:30:00 PM
```
I am getting unexpected results.

```
anytime::anytime("11/26/2018 2:30:00 PM", tz = "CST")
[1] "2018-11-26 06:00:00 CST"
```

I am using anytime 0.3.7 and R 3.6.0

**Comment by eddelbuettel** [comment]
It is a bad input format. We warn against single digits.  Known Boost limitation. Also, AM/PM don't work.  We need 24 hour formats.

```r

> library(anytime)
R> anytime("11/26/2018 02:30:00 PM")  
[1] "2018-11-26 CST"
R> anytime("11/26/2018 02:30:00")  
[1] "2018-11-26 02:30:00 CST"
R> 
```

You can, however, switch to the also-supported code taken from R and it even copes with (but ignores) AM/PM:

```r
R> anytime("11/26/2018 2:30:00", useR=TRUE)  
[1] "2018-11-26 02:30:00 CST"
R> anytime("11/26/2018 2:30:00 PM", useR=TRUE)  
[1] "2018-11-26 02:30:00 CST"
R> 
```

Hope this helps.  Ok to close this?

**Comment by estern95** [comment]
Thank you for your response. Can you point me towards these limitations? It isn't innately clear where these are. I wonder if it would be possible to warn in these cases? Since it doesn't throw a warning when digits are getting scrubbed out, it become difficult to track down bugs. Thank you for your hard work on this package. I use it extensively and find it very useful. Otherwise, okay to close.

**Comment by eddelbuettel** [comment]
It's hard to document code well but this particular case is covered under Notes: in the help page.

See https://github.com/eddelbuettel/anytime/blob/master/R/anytime.R#L56-L59 -- a link to the source from which the .Rd file is generated.  Suggestions welcome, and this is a tricky problem if one aims to work "format-less" as `anytime` does.
