### ISSUE TITLE
Add argument for default MM/DD to add to just YYYY inputs

### ISSUE THREAD

**Issue by npwinkler** [eddelbuettel/anytime#112]
Hello!

Thank you for writing this package! Using it has allowed me to do some things that I couldn't do (at least as easily) in lubridate. 

I see you've implemented anydate parsing just YYYY into YYYY-01-01, which is helpful for getting an estimate. However, 
1) I am working with a case where I want to convert YYYY into YYYY-06-15 for my estimate and don't see a way to do that
2) I think it would be helpful for people to have the ability to input the MM-DD that they want to convert just YYYY's into. Another example of where this would be useful is if the data is originally stored as YYYY but every one is actually from the same MM-DD, e.g. 02-15 and they want to convert it into YYYY-02-15.
(I do believe in case 2 there is an easy workaround of just doing a paste of that MM-DD, e.g. 02-15 at the end of the YYYY string, and it would still be nice, given that if you allow/fix example 1, you also do so for example 2)

Please let me know if there's a way

**Comment by eddelbuettel** [comment]
I answered related questions a few time on StackOverflow.  In short, YYYY-MM is _not a date_ as a date also needs a day.  As such, some of the underlying parsers _will always fail_.  Some parsers are sometimes generous and fill in:

```r
> library(anytime)
> anydate("2020")      ## Boost parser fills in 01 and 01
[1] "2020-01-01"
> 
> anydate("2020", useR=TRUE)        ## R parser refuses
[1] NA
> 

I think your best bet here will be preprocessing.  This is outside the scope of `anytime`.
