### ISSUE TITLE
month year specification

### ISSUE THREAD

**Issue by davidtedfordholt** [eddelbuettel/anytime#115]
I appreciate this package a great deal! Would it be possible to have `%B %Y` parse the way `%Y %B` does?

```
anytime::anydate("2020 January")
[1] "2020-01-01"
anytime::anydate("January 2020")
[1] NA
```

Thank you!

**Comment by davidtedfordholt** [comment]
(This would address https://github.com/tidyverts/tsibble/issues/142#issuecomment-589264625, as well as be nice for me)

**Comment by eddelbuettel** [comment]
You already have the ability to add formats.  Would that be good enough?

```r
R> library(anytime)
R> anytime::anydate("2020 September")
[1] "2020-09-01"
R> anytime::anydate("September 2020")
[1] NA
R> anytime::addFormats("%B %Y")
R> anytime::anydate("September 2020")
[1] "2020-09-01"
R> 
```

**Comment by eddelbuettel** [comment]
In the wider sense, I am actually surprised I support `%Y %B`  :grinning:   So maybe adding `%B %Y` to the end of the list would indeed be easy enough and not create trouble.

**Comment by eddelbuettel** [comment]
The actual formats, if you look at them, all had a day component -- because one _really_ neends Y and M and D to form a _date_ as opposed to a different type you seek here, namely 'month-year' tuples.  

And those work as you desire. You "just" to inject a one.  `September 1 2020` already passes.

**Comment by davidtedfordholt** [comment]
> In the wider sense, I am actually surprised I support `%Y %B`  :grinning:   So maybe adding `%B %Y` to the end of the list would indeed be easy enough and not create trouble.
> 

I went in and mucked about a bit, but my C++ is nearly nonexistent, other than working with QMK, so I couldn't even figure out where `%Y %B` worked. Otherwise, I would have just PRed.

I have only interacted with the package through `tsibble`, but am suddenly thinking about all the moments back in school when this would have saved me sooo much time and headache. The use in `tsibble` is often to create a date from an incomplete object, but then return it to a format for whatever time period the original represented (such as `yearmonth`). You've nearly eradicated the worst part of data cleaning in my life!

**Comment by eddelbuettel** [comment]
It the narrowest sense it is appending here:

https://github.com/eddelbuettel/anytime/blob/7481e69a096cab7cfccd98d92038de1b067a7d64/src/anytime.cpp#L101-L104

as those are the four lines with `Y%` and `%B` -- but as I mentioned they also have `%d` and `%e` (for the days).  

But as I mentioned you don't need it.  Just executed `anytime::addFormats("%B %Y")` before you parse.

**Comment by davidtedfordholt** [comment]
Thank you! I appreciate it a lot.
