### ISSUE TITLE
Returning NA value

### ISSUE THREAD

**Issue by alishersuyunov** [eddelbuettel/anytime#117]
The following expression is returning `NA` instead of expected `2020-10-13`:
`anytime::anydate("13-10-2020")     # %d-%m-%Y`

However, the following is working, but considering as `mdy`:
`anytime::anydate("01-10-2020")`

Are there any solutions to fix such issue without informing the user?

**Comment by eddelbuettel** [comment]
That is documented and intended behaviour:, see for example `help(anytime)` and `help(addFormats)`.  Using a "two digits" "separator" "two digits" format is ambigious. 

So I think we should close this.

**Comment by alishersuyunov** [comment]
Thanks!
Removing `removeFormats("%m-%d-%Y")` format and `addFormats("%d-%m-%Y")` fixed the issue.

**Comment by eddelbuettel** [comment]
Thanks for your understanding.  I (much like everybody else) prefer ISO 8601 by a mile, but one does encounter the 'digits sep digits' format, especially where I live now --- and yes it upsets the more standard d-m-y format even with two-two-four digits.  That is one tradeoff we had to make.   But you'd still be better off with dd-Mon-yyyy if you could :)  

Now, we don't always can but I appreciate that the flexibility of (one-time per run-time) tweaking formats is sufficient for you.  That is how it was planned ;-)
