### ISSUE TITLE
Feature request:  function to return which format was recognized.

### ISSUE THREAD

**Issue by dmurdoch** [eddelbuettel/anytime#120]
In this R-help question:  https://stat.ethz.ch/pipermail/r-help/2021-February/470260.html, the author wants to control the century in conversion of data like this:

```
 name      ddate       anew
1    A   19-10-02 2002-10-19
2    D 11/19/2006 2020-11-19
3    F   9/9/2011 2011-09-09
4   G1 12/29/2010 2020-12-29
5   AA   10/18/93 2093-10-18
```

In the last entry, they wanted 1993 rather than 2093.  I can see two solutions for this:  allow the user to specify how the century is guessed when a two-digit year is given, or let the user know what format was used (in this case it looks like `%m/%d/%y`), so they can manually adjust dates that came from two-digit year formats.  (I'm assuming it would be fine to output 2093-10-18 if the input had been a four-digit year format.)

Maybe specifying the century rule is possible in the library, but I couldn't spot that.  So letting the user fix up two digit mistakes seems like it would be useful.

**Comment by eddelbuettel** [comment]
Interesting.  I guess they would have to override the system library century detection.  

I actually think `anytime` mostly rejects `%y` on principle but users can of course add it.   

I'll look into keeping 'state' with an internal variable about the format used, and an accessor could then report it.

**Comment by eddelbuettel** [comment]
Ok, I looked the original post.  I think the user is simply out ot luck:

```r
> datevec <- c("19-10-02", "11/19/2006", "9/9/2011", "12/29/2010", "10/18/93")    
> anytime::anydate(datevec)           
[1] NA           "2006-11-19" "2011-09-09" "2010-12-29" NA                 
>
```

The first and last formats are clearly discouraged by our documentation: if you use two-year date, you run a risk of bad outcomes.

`anytime` does not try to be a mindreader. It will do _reasoanable_ things for _reasonable_ inputs in a speedy and reliable way with less fuss than most of the alternative (no formats, no "origin", flexible with multiple formats).  But it doesn't master metaphysis: garbage in still leads to garbage out.  I am not sure there is anything actionable _in this r-help email_.

**Comment by eddelbuettel** [comment]
Closed for lack of follow-up.
