### ISSUE TITLE
Anytime errors with length 1 NA

### ISSUE THREAD

**Issue by robitalec** [eddelbuettel/anytime#121]
Hello, 

First off - thanks for this incredible package. A delight to use and love how lightweight it is. 

I ran into an interesting behaviour looping through a bunch of diverse and messy datasets , each with a character column of length 1 to be converted to dates. 

If the data is length = 1 NA, `anytime` returns an error. 
Looking into this further, if the data is length > 1, and includes a valid character and an NA, `anytime` returns a matching NA. 
If the length > 1 all NA, `anytime` returns the same error. 

Here's a simple reprex. Let me know if this is intended behaviour, I can certainly just handle it on my end. 

``` r
library(anytime)

anytime(NA)
#> Error in anytime_cpp(x, tz = tz, asUTC = asUTC, asDate = FALSE, useR = useR, : Unsupported Type

anytime(c(NA, '2015-01-01'))
#> [1] NA               "2015-01-01 NST"

anytime(c(NA, NA))
#> Error in anytime_cpp(x, tz = tz, asUTC = asUTC, asDate = FALSE, useR = useR, : Unsupported Type
```

<sup>Created on 2021-03-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by eddelbuettel** [comment]
Thanks for the kind words.

Cases 1 and 3 are, not to put too fine a comb on it,  "garbage" as there is nothing to parse.  The answer is even consistent and the same:  an error.  

What were you expecting here?   Something like this:   

```r
> as.POSIXct(NA_real_)
[1] NA
> class(as.POSIXct(NA_real_))
[1] "POSIXct" "POSIXt" 
> 
> as.Date(NA_real_)
[1] NA
> class(as.Date(NA_real_))
[1] "Date"
> 
```

Isn't aborting in error better than silently returning `NA`s?

**Comment by eddelbuettel** [comment]
Also, looking at the code and recognising that you it _branches on type_ it makes it a little more like an error on your end _for not supplying a type_:

```r
> library(anytime)
> anytime(as.character(NA))
[1] NA
> anytime(as.numeric(NA))
[1] NA
>
```

I can look into making the final 'default case' more informative. The main culprit, for now, is

```r
> class(NA)
[1] "logical"
> 
```

and I presume it is my error for not responding more plainly to `logical` input. I can fix that.

**Comment by robitalec** [comment]
> Isn't aborting in error better than silently returning NAs?

I would agree this is often the case. 

I opened the issue because it felt like NAs were being treated differently, dependent from my understanding on if there was at least something valid provided to `anytime`. This makes combining different and messy data slightly trickier because for some data, anytime will return an error, and for others it'll return NAs silently. 

I agree though, garbage in, what else are we expecting!

Confirming where I first noticed this class(NA) = "logical".

**Comment by eddelbuettel** [comment]
I think you found a valid bug -- so thanks for bringing it to my attention -- even if we agree that it is a marginal corner case.

You can have NA values just fine but they _have to be typed_ so NA in char, or numeric, or date(time), or ... should work.

**Comment by robitalec** [comment]
Yes - very marginal. I appreciate your help with it. 

Thank you!

**Comment by eddelbuettel** [comment]
My pleasure -- thanks for catching that!  A clearly uncovered condition, even after all those years. I guess I must have felt that a three-valued logical would never come in but what did I know :)
