### ISSUE TITLE
Chinese date format suggestion

### ISSUE THREAD

**Issue by jeffreyxparker** [eddelbuettel/anytime#122]
I might suggest adding in the common Chinese format "%Y年%m月%e日" as a default.

Could I also suggest an improvement to the documentation on `addFormats`?

```
my_date <- "2020.07.07"
anytime(my_date) # does not parse

addFormats("%Y.%m.%d)
anytime(my_date) # parses
```

**Comment by eddelbuettel** [comment]
I don't yet see the connection between "%Y年%m月%e日"  and "2020.07.07".  Am I missing something?  Do "年" and "月" get parsed as "." ? 

Also what do you suggest to add to `help(addFormats)` ?

**Comment by eddelbuettel** [comment]
I just gave it a shot.  As the `%Y` leads I am not that opposed -- it is a variant of the ISO format with `.` as the separator.

I can also put a cross-reference under 'See also' to `addFormats` into the help for `anytime`.

**Comment by eddelbuettel** [comment]
See this branch:  https://github.com/eddelbuettel/anytime/tree/feature/added_format
