### ISSUE TITLE
just yyyy-mm-dd hh:mm:ss but not AEST suffix

### ISSUE THREAD

**Issue by genghiskhanofnz** [eddelbuettel/anytime#124]
Hi there
My system software clinical costing ppm needs the above format.  I have a huge dataset of 500K rows with yyyy-mm-dd format.  But the software import specs needs to add hh:mm:ss to yyyy-mm-dd in the dataset.  Anytime converts 2020-07-02 to 2020-07-02 10:00:00 AEST.  I jsut want the yyyy-mm-dd hh:mm:ss without AEST thing.  Please advise how to achieve this.  Thanks.

**Comment by eddelbuettel** [comment]
I do not follow.  Is your request about the different between the _time_ and _date_ parsers?  Can you show an input element or two?

If you are concerned how a _date_, when parsed as a _time_, get the local timezone added then you can use the tz arguments.

```r
> library(anytime)
> anytime("2021-07-16")
[1] "2021-07-16 EDT"                                 
> anydate("2021-07-16")
[1] "2021-07-16"
> utcdate("2021-07-16")
[1] "2021-07-16"
> utctime("2021-07-16")
[1] "2021-07-15 20:00:00 EDT"
> Sys.getenv("TZ")
[1] ""
> 
```

(This is in a machine without explicit TZ but currently in Eastern Daylight Time.)

Note that the _printed_ display is done by R itself for the object we create, either a `Date` or a `POSIXct` and prints the latter with, and the former without, a timezone display.  But that is just pretty-printing and has no influence on parsing.

**Comment by eddelbuettel** [comment]
Also:

```r
> tt <- anytime("2021-07-16 10:11:12")
> class(tt)
[1] "POSIXct" "POSIXt" 
> format(tt)
[1] "2021-07-16 10:11:12"
> print(tt)
[1] "2021-07-16 10:11:12 EDT"
> 
```

So if instead of relying on the default `print()` method you override your own, even using `format()`, or even just use `format()` to create strings, you should get what you desire.

Does that answer your question?

**Comment by genghiskhanofnz** [comment]
@eddelbuettel  = i will try format() on Monday when I go back to work.  Will get back to you on the outcome.  Appreciated your time and effort in this very quick response.

**Comment by eddelbuettel** [comment]
Another one, by the way, is just to format yourself -- the parse object is a `POSIXTct` so you can also do:

```r
 > now <- Sys.time()    # use your anytime() parsed object here                                                                                                                                          
 > cat("It is now", strftime(now, "%Y-%m-%d %H:%M:%S"), "and we like it without the TZ\n")                                                                    
 It is now 2021-07-16 17:25:29 and we like it without the TZ                                                                                                  
 >  
```

As none of this is a problem in `anytime`, I will close. Please feel free to reopen if you think you have an issue.

**Comment by genghiskhanofnz** [comment]
Thanks.  I will try this @eddelbuettel
