### ISSUE TITLE
`"30081993"` is not understood by `"%d%m%Y"`

### ISSUE THREAD

**Issue by iagogv3** [eddelbuettel/anytime#131]
Hi,

First of all, thanks for this wonderful package.

Reprex:

```r
library(anytime)
removeFormats(getFormats())
ddFormats <- c("%Y-%m-%d", "%d/%m/%Y", "%d %m %Y", "%d-%m-%Y", "%d%b%Y", "%d%m%Y")
addFormats(rev(ddFormats))
anydate("30081993")
#> [1] NA
```

Why is not the string translated to 1993-08-30, when  `"%d%m%Y"` is included as a format?

```
sessionInfo()
#> R version 4.1.3 (2022-03-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19045)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Spanish_Spain.1252  LC_CTYPE=Spanish_Spain.1252   
#> [3] LC_MONETARY=Spanish_Spain.1252 LC_NUMERIC=C                  
#> [5] LC_TIME=Spanish_Spain.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] anytime_0.3.9
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.10       digest_0.6.31     withr_2.5.0       R.methodsS3_1.8.2
#>  [5] lifecycle_1.0.3   magrittr_2.0.3    reprex_2.0.2      evaluate_0.21    
#>  [9] rlang_1.1.0       cli_3.6.1         rstudioapi_0.15.0 fs_1.6.2         
#> [13] R.utils_2.12.2    R.oo_1.25.0       vctrs_0.6.2       styler_1.9.1     
#> [17] rmarkdown_2.25    tools_4.1.3       R.cache_0.16.0    glue_1.6.2       
#> [21] purrr_1.0.1       xfun_0.39         yaml_2.3.7        fastmap_1.1.1    
#> [25] compiler_4.1.3    htmltools_0.5.5   knitr_1.44
```

Although I produced the reprex with R 4.1.3, the issue also happens with R 4.3.2

**Comment by eddelbuettel** [comment]
> First of all, thanks for this wonderful package.

Thanks!

I can reproduce your reprex, but there is very little I can do:  we farm conversion out to the respective libraries (Boost Date_time by default, R's own if you set `useR=TRUE`).  Both fail.  As does R by itself:

```
> as.Date("30081993", "%m%d%Y")
[1] NA
> 
```

I suspect something overflows before the tokens get parsed.  On a hunch, trying this variant supports this line of reasoning at least for the R case:

```r
> as.Date("10081993", "%m%d%Y")
[1] "1993-10-08"
>
```

Between the lines, `anytime` strongly encourages everyone to work with 'sane' formats whereever possible, and help where not.  I doesn't strike me that '%d%m%Y" is not really a perfectly sane format though.  I don't think I can help you much here I am afraid :-/

**Comment by iagogv3** [comment]
Thanks! 

I tried also `useR = TRUE` but then I got other issues (I have an excel column with hundreds of dates with a number of distinct [sane and unsane] formats)
