### ISSUE TITLE
Unexpected shift of day when forcing timezone to GMT

### ISSUE THREAD

**Issue by bobjansen** [eddelbuettel/anytime#18]
The default timezone for my R session is 'Europe/Berlin':

``` R
> anytime:::getTZ()
[1] "Europe/Berlin"
```

However, we strive to store all our data using GMT, so in order to convert the date `20161010` to `POSIXct` I ran

``` R
> anytime(20161010, tz = "GMT")
[1] "2016-10-09 22:00:00 GMT"
```

which, to my surprise, returned 10pm on the previous day. 

Similarly, `anydate` returns the previous day:

``` R
anydate(20161010, tz = "GMT")
[1] "2016-10-09"
```

Is this intentional?

This is what is stored under the hood:

``` R
> dput(anytime(20161010, tz = "GMT"))
structure(1476050400, class = c("POSIXct", "POSIXt"), tzone = "GMT")
> dput(anytime(20161010))
structure(1476050400, class = c("POSIXct", "POSIXt"), tzone = "Europe/Berlin")
```

**Comment by eddelbuettel** [comment]
Thanks for coming here.  I tend to just ignore issues on Twitter which I find wholly inappropriate for these types of questions.

In essence, what adding the `tz` argument does is to _shift the formatted output_.  See:

``` r
R> Sys.getenv("TZ")                       # TZ when loading anytime matters
[1] "Europe/Berlin"
R> library(anytime)
R> anytime(20161010)
[1] "2016-10-10 CEST"
R> anytime(20161010, tz="GMT")            # what you get
[1] "2016-10-09 22:00:00 GMT"
R> format(anytime(20161010), tz="GMT")    # what it is equivalent too
[1] "2016-10-09 22:00:00"
R> 
```

So adding a `tz` to the _output_ shifts the output as _the parsing is always done at local time_.

In essence, we cannot (currently) use the package to parse UTC times.  

That is somewhat restrictive but hard to overcome  in the current format with its "defaults for everything" scheme.  But the thought of adding a 'treat as UTC' facility -- either an option, or a new function `utctime()` -- crossed my mind too.

**Comment by eddelbuettel** [comment]
Here is another illustration:

``` r
R> anytime(as.Date("2016-10-10") + seq(7,21,by=7), tz="GMT")
[1] "2016-10-17 02:00:00 CEST" "2016-10-24 02:00:00 CEST" "2016-10-31 01:00:00 CET" 
R> 
```

**Comment by eddelbuettel** [comment]
Good news:  It was really use to add 'parse as UTC' which I just did on the laptop while on the short commute into work.   Not yet committed but should appear in the next day first as a branch.

Can you build from source and test / comment?

**Comment by bobjansen** [comment]
Yes I can and good news indeed!

**Comment by eddelbuettel** [comment]
Perfect -- I just pushed to [this branch](https://github.com/eddelbuettel/anytime/tree/feature/utcparse) via [this commit](https://github.com/eddelbuettel/anytime/commit/9dc027aabbe1773669ab12ae21fce9cf4f20b1d7).  

This is still pretty raw, but seems to work so far.   I also added `utctime()` and `utcdate()` as shorthands; maybe `anyutctime()` and `anyutcdate()` are better / more defensive choices?

**Comment by eddelbuettel** [comment]
Needed a follow-up fix for something I added at the last minute.  Now two commits on the branch.

**Comment by bobjansen** [comment]
I did some testing and everything worked as expected. Would you like me to add a bunch of tests for this?

**Comment by eddelbuettel** [comment]
Yes, we should.  I was (very loosely) thinking that using UTC takes some more timezone-variability out (and R is pretty heroic here, bringing its own code to Windows for this).  So I could not yet do too many 'hard' tests (via `stopifnot()` as in file [tests/validate.R](https://github.com/eddelbuettel/anytime/blob/master/tests/validate.R)) as those would fail.  I think we can maybe add one or two for UTC tests (which formating to UTC).  Tests testing on Windows though, so easier upload to win-builder or test locally.

Also, the _string (etc) parsing_ logic is the same and unchanged so that is in effect already covered.  Not sure how much we need to double up.

What are your thoughts?  Add a new file in `tests`? Expand an existing one?

**Comment by bobjansen** [comment]
How do you run the tests, are you running all the scripts in tests and inspecting the output visually?

Anyway, I've added some tests in this commit https://github.com/bobjansen/anytime/commit/7e0a7506e221ab25f68ec287ae48a250c1d703a3.

I just realized these tests are not very useful or a developer with a timezone set to either GMT or UTC as the output should not be affected. What would be a clean way to hack around that?

I've also have a commit that removes the .Rout.save files as RStudio tries to run them:

https://github.com/bobjansen/anytime/commit/7e0a7506e221ab25f68ec287ae48a250c1d703a3.

The whole branch has two messed up commits from an accidental merge so I would not recommend merging my branch directly.

**Comment by eddelbuettel** [comment]
I run `R CMD check`.  As you noticed the checks are a little loose for the reasons given earlier--with tighter checks it promptly failed for me on win-builder in Dortmund.  We have to think about a tighter way to test.  I suspect that this

```
R> anytime("01 Feb 2003 04:05:06", tz="UTC", asUTC=TRUE)
[1] "2003-02-01 04:05:06 UTC"
R> 
```

will work anywhere.  I'll add it to `tests/validate.R`.

Something like your commit https://github.com/bobjansen/anytime/commit/7e0a7506e221ab25f68ec287ae48a250c1d703a3 may still help.

The second link has the URL so I don't see that commit.  We should not need it as `.Rbuildignore` already excluded `.Rout.save` -- so as long as you test the way tests are recommended to be run, ie via a .tar.gz created via `R CMD build` then you're already good.  RStudio does the same via `Check Package`.

Git accidents happen to the best of us. I try to keep the tree and branches clean.  That meant that yesterday I squashed twice and that seems to have 'eaten' one of your commits.  I always try very hard to show contributors work so I am genuinely sorry about that.  I am sure you get another one in.
If you have work you want to keep, copy it out and then maybe just `git reset --hard` to a given sha1 and push again.  Or (as some people prefer) just move the current repo to `-saved` or `-old` and fork again.

**Comment by eddelbuettel** [comment]
Let me close this ticket now though -- the (per your title) _"Unexpected shift of day when forcing timezone to GMT"_ is now documented as the effect of the `tz` argument.

Let us discuss extensions, more tests, ... in a new ticket.  Or if you prefer, we can pile'em on here too.

**Comment by bobjansen** [comment]
Thanks, today I learned more about `R CMD check`. 

Let's open a new ticket then and don't worry about the missing commit, it was a tiny amount of work.
