### ISSUE TITLE
should it be better set default tz to UTC

### ISSUE THREAD

**Issue by shrektan** [eddelbuettel/anytime#28]
In https://github.com/eddelbuettel/anytime/blob/master/R/init.R#L46, the default `tz` is set to the system's default tz (`assign("tz", tz, envir=.pkgenv`). 

However, in my opinion, it might be better **always set default tz to UTC**, so the package function is more platform dependent. And if people want it to be system's tz, they should explicitly set it.

**Comment by eddelbuettel** [comment]
Well I did think about this.  Some comments:
- R itself parses to localtime, our behaviour shadows R
- We now have 'published behaviour' which is hard to change (though the package is young)
- There is an internal tz option as of the current master branch (to be released end-of-week I guess) there is a (currently unexported) function you can call:

``` r
R> library(anytime)
R> now <- format(Sys.time())
R> anytime(now)
[1] "2016-10-26 06:01:57.619137 CDT"
R> anytime:::setTZ("Europe/Madrid")
R> anytime(now)
[1] "2016-10-26 13:01:57.619137 CEST"
R> 
```

So `setTZ` pretty much gets you what you want. You had it before too by using the `tz=` argument.

**Comment by shrektan** [comment]
Thanks for your comments. `setTZ` is good enough for me.

**Comment by eddelbuettel** [comment]
We could do one better.  In a few packages, I respect a possible option if set.  So if you wanted to, say, deploy something like this in `~/.Rprofile` 

```
options("anytimeTZoverride" = "Europe/Madrid")     # or any other value like UTC
```

then we could use that, and fall back on finding local as the default.  

Of course, you could just use `TZ=UTC` and then R would already do this for you so it is really, really, really overkill.

``` bash
edd@max:~$ TZ=UTC Rscript -e 'anytime:::getTZ()'
[1] "UTC"
edd@max:~$ TZ=Europe/Berlin Rscript -e 'anytime:::getTZ()'
[1] "Europe/Berlin"
edd@max:~$ 
```

That is actually good enough, methinks.  Plus you do have `anytime:::setTZ()` to "fix" or alter after the fact.

**Comment by shrektan** [comment]
Thanks for the advice. I personally prefer to use `options()` or the function `anytime:::setTZ()` to do this, because I'm kind of conservative on changing the system environment variables, in case of any unexpected side-effect.

**Comment by eddelbuettel** [comment]
I agree on stylistic grounds--I also "hate" TZ but you can set them per-process, R can set them per-project (ie `.Renviron` in working directory) etc pp, in the running R session (just before `library(anytime)`, reset afterwards) etc pp

But you have `setTZ()` so no imminent issues.
