### ISSUE TITLE
Parsing time in a TZ other than localtime or UTC?

### ISSUE THREAD

**Issue by KaraDowney** [eddelbuettel/anytime#32]
Have you ever considered expanding asUTC's functionality to allow users to parse time in any timezone they specify? 

I regularly work with data that is neither in my local timezone nor in UTC. For example, I might receive data with timestamps in strings that should eventually be formatted as POSIXct with an Eastern timezone. I am physically located in California, and my computer's default timezone is Pacific. 

In my standard workflow I would do something like:
```r
> tz <- "America/New_York"
> Sys.setenv(TZ = tz)
> imported_data <- "2016-08-01 01:00:00"
> imported_data <- as.POSIXct(imported_data, format = "%Y-%m-%d %H:%M:%S",  tz = tz)
> imported_data
[1] "2016-08-01 01:00:00 EDT"
```
I'd love to switch to using anytime (so much faster! so much more intuitive!), but I can't get dates to parse in anything other than UTC (with asUTC = T) or my computer's actual localtime (ie PST, regardless of what I set in my R environment). The output is then adjusted to whatever timezone I've specified after the parsing happens, so the above example returns as "2016-08-01 04:00:00" instead of "2016-08-01 01:00:00". Creating the string after changing the R environment timezone also doesn't fix the issue:
```r
> library(anytime)
> imported_data <- "2016-08-01 01:00:00"
> anytime(imported_data)
[1] "2016-08-01 01:00:00 PDT"
> tz <- "America/New_York"
> anytime:::setTZ(tz)
> anytime(imported_data)
[1] "2016-08-01 04:00:00 EDT"
> imported_data2 <- "2016-08-01 01:00:00"
> anytime(imported_data2)
[1] "2016-08-01 04:00:00 EDT"
```

In case it helps, I'm running Windows 10. A colleague running Ubuntu 1604 had the same thing happen:
```r
On Ubuntu, R version 3.3.2:
> library(anytime)
Warning message:
In fun(libname, pkgname) : No TZ information found. Falling back to UTC.
> imported_data <- "2016-08-01 01:00:00"
> anytime(imported_data)
[1] "2016-08-01 08:00:00 UTC"
> tz <- "America/New_York"
> anytime:::setTZ(tz)
> anytime(imported_data)
[1] "2016-08-01 04:00:00 EDT"
> imported_data2 <- "2016-08-01 01:00:00"
> anytime(imported_data2)
[1] "2016-08-01 04:00:00 EDT" 
```

As far as I can tell from reading through some of the closed issues, this is the same problem (wanting to actually PARSE in UTC, as opposed to just convert an already-parsed date to UTC) that led to the creation of the asUTC feature. Would it be possible to get a more flexible implementation that would allow parsing in any specified timezone?

**Comment by eddelbuettel** [comment]
>  Have you ever considered expanding asUTC's functionality to allow users to parse time in any timezone they specify?

Yes, I have.  Long post of your, so bear with me.  But the _tl;dr_ part of it is that the actual parsing code creates a set of  C++ object once at startup that are then hard to move.  So by default we do parse to localtime.  

But maybe other, more pure timezone packages can help?  Here is a smaller one I wrote:

```r
R> library(RcppCCTZ)
R> Sys.time()
[1] "2016-11-28 20:25:47.324866 CST"
R> format(Sys.time(), tz="UTC")
[1] "2016-11-29 02:25:59.020904"
R> toTz(Sys.time(), "UTC", "America/Chicago")
[1] "2016-11-28 20:26:30.806928 CST"                 # my local time
R> format(toTz(Sys.time(), "UTC", "America/New_York"), tz="America/New_York")
[1] "2016-11-28 21:26:58.284965"                     # correctly shifted (and formatted)
R> 
```

**Comment by eddelbuettel** [comment]
That said, one _could_ possibly do what you ask for.  But it is more involved.  I also have some in the RcppBDT package, and it adds a timezone information file.  We would probably need that.

For the reason outlined above it is probably _hard_ to make `anytime()` do what you want.  But I understand the need for this.   Maybe combined with this from `RcppCCZT` you can adjust 'away from local' after having parsed with `anytime()`?

```
R> tzDiff("America/Chicago", "America/New_York", pt)
[1] 1
R> tzDiff("America/Los_Angeles", "America/New_York", pt)
[1] 3
R> 
```

**Comment by eddelbuettel** [comment]
Also, because of what I mentioned re the inner workings, you need to set the TZ _before_ loading `anytime`:

```
R> Sys.getenv("TZ")        # Linux box with config file defining Chicago for me as TZ
[1] ""
R> Sys.setenv("TZ"="America/Los_Angeles")
R> Sys.time()
[1] "2016-11-28 18:48:08.108348 PST"
R> library(anytime)
R> anytime("2016-11-28 18:48:08")
[1] "2016-11-28 18:48:08 PST"
R> 
```

I am still in Chicago but I tricked anytime into thinking I am in LA.

**Comment by eddelbuettel** [comment]
Ok, that was very useful food for thought.  I think we have something.  It is (like all things date, time and timezones) under-documented and confusing.

#### Neil Armstrong Example from CCTZ

I like the CCTZ library on GitHub.  They have [this example](https://github.com/google/cctz#one-giant-leap)

> Moon walk in NYC: 1969-07-20 22:56:00 -04:00
> Moon walk in SYD: 1969-07-21 12:56:00 +10:00

#### In R with RcppCCTZ

 I transcribed it into RcppCCTZ as well:

```r
R> library(RcppCCTZ)
R> helloMoon()
1969-07-20 22:56:00 -0400
1969-07-21 12:56:00 +1000
R> 
```

I tried abstracting a converter function out of it, and it works, but you have to be very careful:

```r
R> format(toTz(anytime::utctime("1969-07-20 22:56", tz="UTC"), "America/New_York", "Australia/Sydney", verbose=TRUE), tz="Australia/Sydney")
1969-07-20 22:56:00 -0400
1969-07-21 12:56:00 +1000
[1] "1969-07-21 12:56:00"
R> format(toTz(anytime::utctime("1969-07-20 22:56", tz="UTC"), "America/New_York", "Australia/Sydney"), tz="Australia/Sydney")
[1] "1969-07-21 12:56:00"
R> 
```

The trick is to remember to set the explicit target timezone also when printing to the console. Hence the `format(x, tz="...")`.   Also important to make the starting point an 'UTC' one, interpreted at the first TZ and then shifted to the second.

I need to possibly clean up one or two more things, check/add some documentation and maybe add a better wrapper.

"But we can do this."   Check back in with me in a bit in case I forget to push this.

**Comment by eddelbuettel** [comment]
Updated versions on both packages are now on CRAN.  I hope this helps you -- I realized after we started this that the RcppCCTZ package is actually not being built for Windows (as it needs information about timezones in a form common on Unix and OS X).
