### ISSUE TITLE
Milliseconds rounding issues

### ISSUE THREAD

**Issue by cactus74** [eddelbuettel/anytime#35]
Dirk,

I was glancing through the anytime functionalities and ended up discovering there must be an issue with rounding.

```
> options(digits.secs=6)
> format(anytime("2016-02-25 17:34:00.376", tz="America/New_York"), "%Y-%m-%d %H:%M:%OS %Z")
[1] "2016-02-25 11:34:00.375999 EST"
> format(anytime("2016-02-25 17:34:00.377", tz="America/New_York"), "%Y-%m-%d %H:%M:%OS %Z")
[1] "2016-02-25 11:34:00.377000 EST"
> format(anytime("2016-02-25 17:34:00.375", tz="America/New_York"), "%Y-%m-%d %H:%M:%OS %Z")
[1] "2016-02-25 11:34:00.375000 EST"
> options(digits.secs=3)
> format(anytime("2016-02-25 17:34:00.376", tz="America/New_York"), "%Y-%m-%d %H:%M:%OS %Z")
[1] "2016-02-25 11:34:00.375 EST"`
```

**Comment by eddelbuettel** [comment]
Formating is done by `format.POSIXct` and is an R _feature_.  Little we can do here, besides formatting ourselves which I'd rather not get into.

**Comment by eddelbuettel** [comment]
Demonstration not involving any code of this package:

```r
R> txt <- c("2016-02-25 17:34:00.375",
+          "2016-02-25 17:34:00.376",
+          "2016-02-25 17:34:00.377")
R> pt <- as.POSIXct(txt)
R> pt
[1] "2016-02-25 17:34:00.375 CST"
[2] "2016-02-25 17:34:00.375 CST"
[3] "2016-02-25 17:34:00.377 CST"
R> 
```

My default is already `options(digits.secs=6)` which I didn't change.  I'll close this as it really is an R issue.  I don't like it either but that is the way it it,  And even when using Boost to format, we get the same issue:

```r
R> anytime:::testFormat("%Y-%m-%d %H:%M:%S%f", txt[1])
[1] "2016-02-25 17:34:00.375 CST"
R> anytime:::testFormat("%Y-%m-%d %H:%M:%S%f", txt[2])
[1] "2016-02-25 17:34:00.375 CST"
R> anytime:::testFormat("%Y-%m-%d %H:%M:%S%f", txt[3])
[1] "2016-02-25 17:34:00.377 CST"
R> 
```

**Comment by eddelbuettel** [comment]
Minor thinko on my part in the last bit.  That isn't Boost formating the output. I may have a different helper for that or try one.

But the issue in this report is still with `format.POSIXct()` and hence an R issue.

**Comment by eddelbuettel** [comment]
But there is hope.  I just added a `format()` function to Rcpp in the transition to the 'new' Datetime classes.  Using that, we can do

```r
options(width=50)
print(anytime:::format(pt))
```

which yields

```bash
edd@max:~/git/anytime(master)$ Rscript /tmp/formating.R 
[1] "2016-02-25 17:34:00.375000"
[2] "2016-02-25 17:34:00.376000"
[3] "2016-02-25 17:34:00.377000"
edd@max:~/git/anytime(master)$ 
```

I'll roll that out in anytime at some point -- I can't quite depend on that yet as not all Rcpp installations have it.  And by the same token, I can probably take a shortcut and put a `format()` routine based on Boost in.

**Comment by cactus74** [comment]
That this could have been a pure R issue did not even come to my mind. Great to hear this can be overcome in the near future using your format() routine. Thanks a lot.

**Comment by eddelbuettel** [comment]
It's messy. I just looked at it on the train -- where code comments by myself reminded me that I had looked into this.  But in order to use Boost code for string formatting, we need the Boost timezone file which this package does not have :-/  RcppBDT so maybe we can suggest it.

Longer term the Rcpp-based solution will do.
