### ISSUE TITLE
ISO 8601 dates: TZ is ignored

### ISSUE THREAD

**Issue by Inventitech** [eddelbuettel/anytime#42]
Hi,

I just ran into this issue and was wondering why anytime-0.2.0 truncated the TZ information.
For example, `anytime("2011-09-08T18:49:05-07:00")` returns `[1] "2011-09-08 18:49:05 CEST"`, which is just wrong.

 Wouldn't it be better to
- support the TZ (compare parsedate for ISO 8601)?
- at least give a warning in that case?

Thx!

**Comment by eddelbuettel** [comment]
They are generally always ignored on input, and [that is documented](http://www.boost.org/doc/libs/1_63_0/doc/html/date_time/date_time_io.html#date_time.format_flags).  That sucks a little but such is life.

Ok if we close this?

**Comment by Inventitech** [comment]
Sure, I just doubt that this will be obvious to your users given the project goal `anytime() aims to be that general purpose converter returning a proper POSIXct (or Date) object no matter the input (provided it was somewhat parseable)`. So I'd very much encourage you to make this more explicit. Especially since searching for ISO 8601 on the boost documentation does not return the desired info, and at least I cannot infer that the TZ info will be swallowed from "ISO time zone (output only). This flag is ignored when using the time_facet with a ptime."

**Comment by eddelbuettel** [comment]
You are reading too much into this.  We heuristically try a bunch formats. None includes TZ _because we can't_.  No more, no less.
