### ISSUE TITLE
anytime not handling Dutch month abbreviations

### ISSUE THREAD

**Issue by jaapwalhout** [eddelbuettel/anytime#45]
Today I ran into an issue with pasing Dutch date strings.

A reproducible example:

```
# setting the locale to Dutch
Sys.setlocale("LC_TIME", "nl_NL.UTF-8")
```

Using `anydate` seems to fall back to UTC:

```
# Dutch month abbreviation doesn't work
> anydate("2013-mrt-14")
[1] NA

# English one does
> anydate("2013-mar-14")
[1] "2013-03-14"
```

Specifying the timezone with the `tz` parameter doesn't work either:
```
> anydate("2013-mrt-14", tz = 'Europe/Amsterdam')
[1] NA
```

Any idea what might be wrong?

**Comment by eddelbuettel** [comment]
Ok, after some digging I learned something.  A good first example was here:
http://www.boost.org/doc/libs/1_54_0/libs/locale/doc/html/hello_8cpp-example.html

The upshot is that we would have to _link_ with the boost_locale library. [ Other boost libraries are also needed once strings, or regex, or ... are needed. ] Whereas everything we do is header-only for portability and easier builds.

So in short, looks like we can't do this for anytime.  Sorry!

**Comment by jaapwalhout** [comment]
Thank you for looking into this. It's a pitty that this can't be solved for anytime. Luckily I can fall back to the base R methods
