### ISSUE TITLE
Minor Copy Correction

### ISSUE THREAD

**Issue by russellpierce** [eddelbuettel/anytime#53]
Opening issue for minor copy correction before opening a PR: https://github.com/eddelbuettel/anytime/compare/master...drknexus:patch-1

> The is a known issue (discussed at length in

to 

> There is a known issue (discussed at length in

**Comment by eddelbuettel** [comment]
I think I meant to say _This_ is a known issue...

**Comment by russellpierce** [comment]
Surrounding context:

> ##' The Boost Date_Time library cannot parse single digit months or
> ##' days. So while \sQuote{2016/09/02} works (as expected),
> ##' \sQuote{2016/9/2} will not. Other non-standard formats may also
> ##' fail.
> ##'
> ##' There is a known issue (discussed at length in
> ##' \href{https://github.com/eddelbuettel/anytime/issues/5}{issue
> ##' ticket 5}) where Australian times are off by an hour. This seems
> ##' to affect only Windows, not Linux.
> ##'
> ##' When given a vector, R will coerce it to the type of the first
> ##' element. Should that be \code{NA}, surprising things can
> ##' happen: \code{c(NA, Sys.Date())} forces both values to
> ##' \code{numeric} and the date will not be parsed correctly (as its
> ##' integer value becomes numeric before our code sees it). On the
> ##' other hand, \code{c(Sys.Date(), NA)} works as expected parsing as
> ##' type Date with one missing value. See
> ##' \href{https://github.com/eddelbuettel/anytime/issues/11}{issue
> ##' ticket 11}) for more.

Are you sure you want 'this'?  It reads like a separate issue.

**Comment by eddelbuettel** [comment]
Ah, yes, context helps.
