### ISSUE TITLE
new format, possibly

### ISSUE THREAD

**Issue by rsieg** [eddelbuettel/anytime#55]
Not a bug. Old USGS river flow files, widely consulted, use the following datetime format:
19881001001500 PDT. Anytime seems unhappy with this format.

**Comment by eddelbuettel** [comment]
As in '1988-10-01 00:15:00' ?  It's a wee bit nonstandard but you could try this:

```r
R> library(anytime)
R> anytime:::addFormats("%Y%m%d%H%M%S")
R> anytime("19881001001500")
[1] "1988-10-01 CDT"
R> 
```

but it seems to discard the time part.  So it would need special treatment.  Not sure I want to go there for a (pardon the bluntness) non-standard format.
