### ISSUE TITLE
Occasionally producing inconsistent results

### ISSUE THREAD

**Issue by renkun-ken** [eddelbuettel/anytime#67]
Occasionally `anydate()` produces inconsistent results with integer representing dates in `yyyyMMdd` format. But it's not easy to constantly reproduce.

```r
> anytime::anydate(20160101L)
[1] "1400-01-01"

> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 24 (Server Edition)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.3        Rcpp_0.12.11       RApiDatetime_0.0.3 anytime_0.3.0     
```

**Comment by eddelbuettel** [comment]
The numeric input case is really a special case, which just got a little cleanup.   What we have now is trying to be more consistent with respect to `Date` (and `POSIXct` for `anytime`) -- for "offset" values.  So `anydate(7L)` is seven days past the epoch, and `anytime(3600L)` is an hour past the epoch.

For 'large' values we fall back to parsing, and the numbers are converted to string first.

There is a debug flag you can set via `anytime:::setDebug(TRUE)`.  Can you try?  When I do that I get this right now  (R 3.4.0, Ubuntu). 

```r
R> anytime::anydate(20160101L)
before tests: 20160101
In: 20160101 out: 20160101 and 
s: 20160101 len: 8 res: 1
In:  out:  and 
s: 2016-01-01  one: 2016-01-01 two:   three: 
before parse: 2016-01-01 
days 16801
[1] "2016-01-01"
R> 
```

**Comment by renkun-ken** [comment]
Thanks! I'll try this. It's hard to reproduce this until it corrupts something silently...

**Comment by renkun-ken** [comment]
This problem is reproduced somehow. Following is the debug info:

```
> anytime::anydate(20160101L)
[1] "1400-01-01"
> anytime:::setDebug(TRUE)
[1] TRUE
> anytime::anydate(20160101L)
before tests: 20160101
In: 20160101 out: 20160101 and 
s: 20160101 len: 8 res: 1
In:  out:  and 
s: 2016-01-01  one: 2016-01-01 two:   three: 
before parse: 2016-01-01 
days 4294759108
[1] "1400-01-01"
```

Hope it's helpful.

**Comment by eddelbuettel** [comment]
Not really :-/  as I cannot reproduce.  

But the debug steps tell us that the string `2016-01-01` is created correctly, and then `stringToTime()` is called.   Which calls `ptToDouble()` (after trying the formats). And there we do

```c++
  if (asDate) {
        if (debug) Rcpp::Rcout << "days " << pt.date().day_number() - timet_start.date().day_number() << std::endl;
        return static_cast<double>(pt.date().day_number()) - static_cast<double>(timet_start.date().day_number());
    }
```

This would indicate that your system has an issue with Boost date conversion.  Which sounds ... weird.

All this code is also tickled by the unit tests.  Could you possibly try local debugging via some Boost examples etc pp?   I could email you snippets...

**Comment by renkun-ken** [comment]
No more observations so far.
