### ISSUE TITLE
anytime is overwriting inputs

### ISSUE THREAD

**Issue by christophsax** [eddelbuettel/anytime#68]
This is such a useful package, thanks!

But when I use any of the functions on numeric output, it overwrites the input variable for some reason... 

It works fine with integer or character input.

Here's an example:

``` r
  library(anytime)

  # this works fine
  x <- "1949-01-01"
  b <- anytime(x)
  x  # i.e., x is not modified
#> [1] "1949-01-01"

  x <- -662688000
  b <- anytime(x)
  x  # x is now equal to b !!!
#> [1] "1949-01-01 01:00:00 CET"

  # If I am feeding an integer, everything is fine again...
  x <- -662688000L
  b <- anytime(x)
  x  
#> [1] -662688000
```

**Comment by eddelbuettel** [comment]
Yes, well it is standard R / Rcpp / SEXP-is-a-pointer behaviour. When a SEXP goes in, and we don't need to "cast" it is the variable being carried through.

Here things are a little funny because we either will return a POSIXct (for `anytime` and variants) or Date.

**Comment by eddelbuettel** [comment]
In the middle case (for numeric) this is unavoidable.  We just recast -- the numeric payload is unchanged but we just did a `as.POSIXct()` so now have a class attribute when before you had not.  For the last one it is different as the integer from input becomes a numeric in order to be a POSIXct.

**Comment by eddelbuettel** [comment]
I think the fix would be to add a force clone (ie copy in different memory location) right here: https://github.com/eddelbuettel/anytime/blob/master/src/anytime.cpp#L459

That could be done, I just don't know if it is useful.   I presume because `as.POSIXct()` leaves its input alone, we should too?

```r
R> x <- -662688000 + 3600*6   ## offset for my TZ
R> b <- as.POSIXct(x, origin="1970-01-01")
R> b
[1] "1949-01-01 CST"
R> x
[1] -662666400
R> 
```

**Comment by eddelbuettel** [comment]
Fix coming right up in a branch-that-will-be-a-PR-soon:

```r
R> library(anytime)
R> x <- -662688000 + 3600*6 ; x
[1] -662666400
R> b <- as.POSIXct(x, origin="1970-01-01"); b
[1] "1949-01-01 CST"
R> x
[1] -662666400
R>
```

**Comment by christophsax** [comment]
Nice! Thanks!! 👍

**Comment by eddelbuettel** [comment]
Looking at my last comment I copied the wrong example:

```r
R> library(anytime)
R> x <- -662688000 + 3600*6 ; x
[1] -662666400
R> b <- anytime(x); b
[1] "1949-01-01 CST"
R> x
[1] -662666400
R> 
```
