### ISSUE TITLE
asUTC=TRUE isn't working as expected

### ISSUE THREAD

**Issue by tareefk** [eddelbuettel/anytime#71]
I could be misunderstanding the purpose of the parameter, but I was hoping that passing asUTC = TRUE would result in the first response having a Z at the end indicating that it is in UTC time.

> rfc3339(anytime(today()-1, asUTC = TRUE))
[1] "2017-07-15T20:00:00-0400"
> rfc3339(anytime(today()-1, asUTC = FALSE))
[1] "2017-07-15T20:00:00-0400"

**Comment by eddelbuettel** [comment]
From the help page:

>    asUTC: A logical value indicating if parsing should be to UTC;
          default is false implying localtime.

It is equivalent to using `utctime()` instead of `anytime()` _with_ the flag:

```r
R> anytime("2017-07-17 10:00:00")  # my local time
[1] "2017-07-17 10:00:00 CDT"
R> utctime("2017-07-17 10:00:00")  # utc
[1] "2017-07-17 05:00:00 CDT"
R> anytime("2017-07-17 10:00:00", asUTC=TRUE)  
[1] "2017-07-17 05:00:00 CDT"
R> 
```

Note how the last two are the same, and different from the first.

**Comment by tareefk** [comment]
I think I figured out a better reprex.  The issue seems to be related to the parsing of a Date object. 

Using the example you have above.
> problem_date <- as.Date("2017-07-17")
> anytime(problem_date)
[1] "2017-07-16 20:00:00 EDT"
> utctime(problem_date)
[1] "2017-07-16 20:00:00 EDT"
> anytime(problem_date, asUTC = TRUE)
[1] "2017-07-16 20:00:00 EDT"
> good_date <- "2017-07-17 10:00:00"
> anytime(good_date)
[1] "2017-07-17 10:00:00 EDT"
> utctime(good_date)
[1] "2017-07-17 06:00:00 EDT"
> anytime(good_date, asUTC = TRUE)
[1] "2017-07-17 06:00:00 EDT"
>

**Comment by tareefk** [comment]
Actually, this same issue can be seen if you happen to start with a POSIXct object.

> bad_date <- as.POSIXct("2017-07-17 10:00:00")
> bad_date
[1] "2017-07-17 10:00:00 EDT"
> anytime(bad_date)
[1] "2017-07-17 10:00:00 EDT"
> utctime(bad_date)
[1] "2017-07-17 10:00:00 EDT"
> anytime(bad_date, asUTC = TRUE)
[1] "2017-07-17 10:00:00 EDT"

**Comment by tareefk** [comment]
Nevermind, it looks like it is not the intention of this package to be able to handle any objects.  My apologies.  I was hoping to be able to use it on computed date objects.

**Comment by eddelbuettel** [comment]
I honestly do not understand what you are after.  `Date` types are recognized as such as converted just fine as you saw above.  That is exactly what R itself does:

```r
R> library(anytime)
R> as.Date("2017-07-17")
[1] "2017-07-17"
R> anytime(as.Date("2017-07-17"))
[1] "2017-07-16 19:00:00 CDT"
R> as.POSIXct(as.Date("2017-07-17"))
[1] "2017-07-16 19:00:00 CDT"
R> 
```

If you intend to shift timezone then you look at the wrong package -- check out [RcppCCTZ](https://github.com/eddelbuettel/rcppcctz) for that.
