### ISSUE TITLE
anytime::getTZ and setTZ are not accessible

### ISSUE THREAD

**Issue by tareefk** [eddelbuettel/anytime#72]
Using the RStudio IDE, the getTZ() and setTZ() functions are not available. 
I am guessing that neither one of them is exported.

**Comment by eddelbuettel** [comment]
What are you talking about? They are unexported functions in the package -- standard practice.
Use three colons:

```r
R> anytime:::getTZ()
[1] "America/Chicago"
R>
```

Please consider using the r-help list for elementary R questions.  I can't teach you R here issue ticket by issue ticket.

**Comment by tareefk** [comment]
> anytime::getTZ()
Error: 'getTZ' is not an exported object from 'namespace:anytime'

I get that in both RStudio and from R outside the IDE.

**Comment by eddelbuettel** [comment]
`::`  != `:::`   

As I said:  three colons.  Not two.
