### ISSUE TITLE
Wrongfully recognition with %m/%d/%y

### ISSUE THREAD

**Issue by Wistarr** [eddelbuettel/anytime#74]
I want to convert strings that are formatted as such `01/15/17` (January 15th 2017). But when I add the `%m/%d/%y` formats, it recognises random strings as date. 

```
library(anytime)
string <- "121013_3_1"
anytime(string) #NA

addFormats(c("%m/%d/%y"))
anytime(string) #1999-12-01 UTC
```

Interestingly, it seems like many characters are actually ignored. 
```
vector <- c("121013_3_1", "1210111", "12z01z_3_1", "121013_3$1")
all(anytime(vector) == "1999-12-01 UTC") #TRUE
```

Is there another more specific format I could use?

**Comment by eddelbuettel** [comment]
I am not sure what you are expecting.  `anytime()` and `anydate()` test a fairly large, known, and documented set of formats as a convenience.

If you have an obscure new format, use `as.Date()` with the format string. If need, loop over several inputs with several formats. 

As for `%y` : I recommend against, just how I recommend against non-iso8661 formats (but living where I do I grudgingly accept the m-d-y variant).

I plan to close this unless you manage to convince that there is shortcoming in `anytime()` vis a vis its documented behaviour.  So far we mostly have you wishing for something we never said we'd do.

**Comment by eddelbuettel** [comment]
Also

```r
R> library(anytime)
R> anytime::addFormats("%m/%d/%y %H:%M:%S")
R> anytime("03/04/05 06:07:08")
[1] "2005-03-04 06:07:08 CST"
R> 
```

So I am not sure what the question is here.

**Comment by Wistarr** [comment]
I think `%m/%d/%y %H:%M:%S` was the answer I was looking for. It make the recognition much more precise and resolve the issue I stated.

**Comment by eddelbuettel** [comment]
Yes, while writing it I realized you may "simply" have confused the formats between `anytime()` (needs hour/min/sec) and `anydate()` (does not).  All good then.

And yes, executive decision at my end to prefer four-digit years so the default formats are all with `%Y`.
