### ISSUE TITLE
Thanks & Get back index into format array that matched each date/time?

### ISSUE THREAD

**Issue by ds4ci** [eddelbuettel/anytime#8]
Derk, This is fantastic. I all too frequently get files with inconsistent date/time formats in a column (thanks mostly to Excel!). One feature request: When doing data quality audits, it would be useful to show the frequency of each format in the input stream which would be trivial if there was an option to return the index of format rather than the date/time. -Jim

**Comment by eddelbuettel** [comment]
My name is Dirk, that is an _i_ as in Kirk, but I am glad you find it helpful.   

As for index match, I think you can code that at your end now that we return the format list to you.  One issue may be ... that this is possibly non-unique as several patterns may fit.

**Comment by eddelbuettel** [comment]
This feature request is a little outside the scope of anytime.   Pull request are welcome, of course.
