### ISSUE TITLE
Update documentation to reflect anydate/anytime use on large int

### ISSUE THREAD

**Issue by grandtiger** [eddelbuettel/anytime#83]
Here is the result of running the example on Windows 10 Pro version 1803. The dates are wrong. Is this expected? Any workaround for this issue? Thanks!

```
> library(anytime)
> options(digits.secs=6)                ## for fractional seconds below
> Sys.setenv(TZ=anytime:::getTZ())      ## helper function to try to get TZ
> anytime(20160101L + 0:2)
[1] "1970-08-22 04:01:41 EDT" "1970-08-22 04:01:42 EDT" "1970-08-22 04:01:43 EDT"
```

**Comment by eddelbuettel** [comment]
Thanks, that is an old example that needs updating -- what was the source for the example?  

See the help pages for changes introduced for that format in version 0.3.0 -- it was a bad heuristic _for dates_ that needed changing.  You can get the old behaviour back if you set an option, see the docs.

Also note

```r
R> anydate(20160101L + 0:2)
[1] "2016-01-01" "2016-01-02" "2016-01-03"
R>
```

You can also check with the numerous unit tests.

**Comment by grandtiger** [comment]
@eddelbuettel Thanks for your help! anydate works! The source is http://dirk.eddelbuettel.com/code/anytime.html

**Comment by eddelbuettel** [comment]
Thanks, I suspect it was there. It also seems to (still) be in the `README.md` and some other places. I'll chase it.

**Comment by eddelbuettel** [comment]
Just committed a fix, will update my webpage next. Thanks a lot for catching this!

**Comment by grandtiger** [comment]
You are very welcome! Thanks for your great work!
