### ISSUE TITLE
RFC 3339

### ISSUE THREAD

**Issue by ANetTow** [eddelbuettel/anytime#85]
In the output for `rfc3339`, the UTC offset should have a colon:  "+00:00" instead of "+0000".

**Comment by eddelbuettel** [comment]
Thanks for the report.  

I am not actually writing that myself -- but rather rely on R's `format()` for Datetime objects.

See [here for the code](https://github.com/eddelbuettel/anytime/blob/master/R/formats.R#L81-L90), and this quick example using just R (and my default of microsecond resolution).

```sh
edd@rob:~$ Rscript -e 'format(Sys.time(), "%Y-%m-%dT%H:%M:%OS%z")'
[1] "2018-12-04T11:51:37.690171-0600"
edd@rob:~$
```

The help page for `format.POSIXct` has

```
     ‘%z’ Signed offset in hours and minutes from UTC, so ‘-0800’ is 8
          hours behind UTC. Values up to ‘+1400’ are accepted.
          (Standard only for output.)
```

so this seems on purpose.

**Comment by eddelbuettel** [comment]
Closing this as it reflects standard R behavior.
