### ISSUE TITLE
one hour difference for "Europe/London"

### ISSUE THREAD

**Issue by earowang** [eddelbuettel/anytime#86]
Hi Dirk,

I have run through all possible time zones specified [here](https://github.com/eddelbuettel/anytime/blob/master/tests/bulkTest.R). There's always one hour difference for London, regardless of date-time inputs and OS. Other time zones work as expected. 

``` r

test_timezone <- function(tz) {
  withr::local_envvar(c("TZ" = tz))
  x <- "2016-12-09 09:10"
  format(anytime::utctime(x, tz = "UTC"))
}
test_timezone("Europe/London")
#> [1] "2016-12-09 10:10:00"
```

<sup>Created on 2018-12-08 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by eddelbuettel** [comment]
Sure, but why a new ticket?  Did you see #51 and also #36 and #59?

**Comment by earowang** [comment]
Oops, sorry for the duplicate.

**Comment by eddelbuettel** [comment]
Well I wish it wasn't a dupe or even single bug in the sense that I wish that Boost did the right thing here but something seems vexed with London :-/   There has not been that much development upstream to that part of Boost so I am not sure this will ever get perfect.  Which was part of the reason I added the R fallback.   Not perfect, but I have not been able to come up with something better.

**Comment by earowang** [comment]
R's fedora likely sets system time zone to "Europe/London", that's why some unit tests failed. Now I skip these tests for London, `rhub::check_on_fedora()` works fine.

**Comment by eddelbuettel** [comment]
Good to know you have a workaround.  I can't quite work out whether the bug simply is that UTC (which has no daylight savings) and Europe/London (which has) are confused here and a weird correction is in place -- as UTC is often substituted in when nothing else is set.

In any event, it is a known wart for `anytime` which farms this out to ... something that gets this setting wrong.  But most importantly your package is no longer affected as you found a workaround.  In case you think of a way in which I could or should document this better let me know.  That side we can always improve.

**Comment by earowang** [comment]
Re `?Sys.time()`:
> A time zone region may be known by several names: for example "Europe/London" is also known as GB, GB-Eire, Europe/Belfast, Europe/Guernsey, Europe/Isle_of_Man and Europe/Jersey.

Several alternatives of "Europe/London" have no problem.
``` r
tzvec <- c(
  "Europe/London",
  "GB",
  "GB-Eire",
  "Europe/Belfast",
  "Europe/Guernsey",
  "Europe/Isle_of_Man"
)
test_timezone <- function(tz) {
  withr::local_envvar(c("TZ" = tz))
  x <- "2016-12-09 09:10"
  format(anytime::utctime(x, tz = "UTC"))
}

for (i in seq_along(tzvec)) {
  print(callr::r(test_timezone, args = list(tz = tzvec[i])))
}
#> [1] "2016-12-09 10:10:00"
#> [1] "2016-12-09 09:10:00"
#> [1] "2016-12-09 09:10:00"
#> [1] "2016-12-09 09:10:00"
#> [1] "2016-12-09 09:10:00"
#> [1] "2016-12-09 09:10:00"
```

<sup>Created on 2018-12-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
Since `Australia/Melbourne` also involves DST, but I haven't experienced the same issue as `Europe/London`. I'm not sure it's related to DST.

In addition to skipping tests, I've also added a warning if system time zone is set to `Europe/London` in the function, which users should be made aware of unexpected results.

I would also add a new section in the documentation regarding `Europe/London`, suggesting users could specify the time zone to other names using `Sys.setenv(TZ = ?)`.

**Comment by eddelbuettel** [comment]
Good stuff. But you based this on the R documentation and parameters. Whereas `anytime` is based on Boost code and parameterisations. 

_Edit:_ Disgregard that comment. I was commenting from my phone.

**Comment by eddelbuettel** [comment]
> Several alternatives of "Europe/London" have no problem.

That had been my best line of defence too. Almost as if it is used as / confused with `UTC`.

**Comment by eddelbuettel** [comment]
The pointer from `?Sys.time()` is good.  I just added that to the help page in this commit 375e77cc8ad5f99c9c1950b9351bb1a9a1010a3c (though I mistakenly attributed it to #84 instead of this #86 in the commit message).

**Comment by earowang** [comment]
My bad. It's `?Sys.timezone()`.

**Comment by eddelbuettel** [comment]
Dang.  I couldawouldashoulda have checked myself. Will fix.

Done: 36b627d
