### ISSUE TITLE
typo in package intro

### ISSUE THREAD

**Issue by dracodoc** [eddelbuettel/anytime#9]
[Very minor typo](http://dirk.eddelbuettel.com/code/anytime.html)

`R> install.package("anytime")`

should be

`R> install.packages("anytime")`

**Comment by eddelbuettel** [comment]
Dang, and thanks. I think I do that wrong more often than not.   

Will fix in webpage and possibly also the README.

**Comment by eddelbuettel** [comment]
Fixed in two places.  Thanks!

**Comment by eddelbuettel** [comment]
Also fixed in two places for [gettz](http://dirk.eddelbuettel.com/code/gettz.html).
