### ISSUE TITLE
[FR] support anytime::anydate(180101) => 2018-01-01

### ISSUE THREAD

**Issue by shrektan** [eddelbuettel/anytime#93]
Hi,

I really want to use this light-weight package, converting anything to date or time. Currently, I use `lubridate::ymd()` for this. The latter is much heavier (since I usually only use this single function) and much slower (40x times). 

However, there's one case that `lubridate::ymd()` works relatively better, which is `lubridate::ymd(180101)` returns the date 2018-01-01, while `anytime::anydate(180101)` returns date 2463-02-06. 

I know I can get the correct result by using `anytime::anydate(20180101)`  but I really prefer to use 180101. Only type 6 digits for a date really matters (it's actually 25% more efficient! :P), considering I'm doing this tons of times per day.

Is it possible to support this? If there's no particular reason for not supporting this, I would be happy to investigate to see if I can make a PR...

Thanks!

**Comment by eddelbuettel** [comment]
I hear you and see where you are coming from but I would rather _not_ do that in the released version.

Heuristically determining a date is feasible if done carefully.  We already have to make one judgment call about mm/dd or dd.mm ordering.  Mixing it up with yy versus yyyy is too much.

But if you need it, and are confident in your data, then the `anytime::addFormats()` function is already your friend:

```r
R> library(anytime)
R> addFormats("%y%m%d")             ## declare %y%m%d
R>
R> anytime("180101")                ## use it
[1] "2018-01-01 CST"
R> anytime("180408")                ## check m before d
[1] "2018-04-08 CDT"
R> 
```

So ok to close?

**Comment by shrektan** [comment]
Yes, I think it's good enough for  me. Thanks for your quick response.
