### ISSUE TITLE
More confusion with TZ under Windows

### ISSUE THREAD

**Issue by christophsax** [eddelbuettel/anytime#98]
To make things worse: any idea why `useR = TRUE` stripes the first three letters? This is with my latest dev:

``` r
tz <- "America/Atikokan"
Sys.timezone()
#> [1] "Europe/Berlin"
Sys.setenv("TZ"=tz)
Sys.timezone()
#> [1] "America/Atikokan"
library(anytime)
anytime:::.pkgenv$tz
#> [1] "America/Atikokan"
anytime("2016-09-01 10:11:12", useR = TRUE)
#> Warning in as.POSIXlt.POSIXct(x, tz): unknown timezone 'rica/Atikokan'
#> [1] "2016-09-01 04:11:12 EST"
Sys.timezone()
#> [1] "rica/Atikokan"
```

<sup>Created on 2019-06-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Perhaps I should go to sleep...

**Comment by eddelbuettel** [comment]
> Perhaps I should go to sleep...

Yes.  I usually conclude that when fighting TZ code and system libraries....

And please do not open a new issue every five minutes.  Do you mind closing this and keeping *what is really the same discussion* in #96?  Or am I missing something novel?

**Comment by eddelbuettel** [comment]
Thanks!
