### ISSUE TITLE
single digit dates with unambiguous month and year

### ISSUE THREAD

**Issue by millerjef** [eddelbuettel/anytime#99]
I am trying to parse:
`anydate("August 4, 2018")`

This returns NA. Frankly, this is consistent with the documentation in that `anydate` doesn't handle single digit days; however, I would argue that with the explicit month (August) and year (2018) that the algorithm (Boost Date_Time library) should be able to process this. Perhaps this issue is really with Boost Date_Time, if so, please let me know and I will post there.

Thanks! I appreciate your package!

**Comment by eddelbuettel** [comment]
It's a Boost limitation together with a not-present-by-default format:

```r
> library(anytime)
> addFormats("%B %d, %Y")
> anydate("August 04, 2018")
[1] "2018-08-04"
> 
```

It requires the 0 I am afraid, and I can see little that can be done here.

**Comment by eddelbuettel** [comment]
Closing as duplicate, see 

- [#24](https://github.com/eddelbuettel/anytime/issues/24)
- [#70](https://github.com/eddelbuettel/anytime/issues/70)

You can use `useR=TRUE` for the R parseer.

**Comment by eddelbuettel** [comment]
Good news - this now works in master (and hence the next release probably at the end of the month):

```r
 R> anydate("August 4, 2018")
 [1] "2018-08-04"
 R>
```

**Comment by millerjef** [comment]
Great news! Thank you!

**Comment by eddelbuettel** [comment]
Yes, makes me happy too as this was a wart. A bit embarassed it too me so long to find the obvious fix.  But better late than never :grinning:
